[package]
name = "day_21"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
cached = "0.54.0"
itertools = "0.13.0"
rayon = "1.10.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
